export const attributeNames = {
  architecture:         "Architecture",
  aspectRatio:          "Aspect Ratio",
  audioFeatures:        "Audio Features",
  audioJack:            "Audio Jack",
  availableStorage:     "Available Storage",
  battery:              "Battery",
  batteryCapacity:      "Battery Capacity",
  batteryRemovable:     "Removable Battery",
  batteryTalkTime:      "Battery Talk Time",
  batteryType:          "Battery Type",
  benchMarks:           "Benchmarks",
  bezelLessDisplay:     "Bezel-less Display",
  bluetooth:            "Bluetooth",
  chipset:              "Chipset",
  colours:              "Colors",
  comparePrices:        "Compare Prices",
  cpu:                  "CPU",
  customUi:             "Custom UI",
  dimensions:           "Dimensions",
  displayType:          "Display Type",
  expandable:           "Expandable Storage",
  expertRating:         "Expert Rating",
  fingerpringType:      "Fingerprint Type",
  fingerprintPosition:  "Fingerprint Position",
  fingerprintSensor:    "Fingerprint Sensor",
  fmRadio:              "FM Radio",
  frontAutofocus:       "Front Autofocus",
  frontCamera:          "Front Camera",
  frontCameraSetup:     "Front Camera Setup",
  frontFlash:           "Front Flash",
  frontResolution:      "Front Resolution",
  frontVideo:           "Front Video",
  gps:                  "GPS",
  graphics:             "Graphics",
  hdr:                  "HDR",
  imageURL:             "Image URL",
  internalMemory:       "Internal Memory",
  launchDate:           "Launch Date",
  loudSpeaker:          "Loudspeaker",
  material:             "Material",
  networkSupport:       "Network Support",
  nfc:                  "NFC",
  operatingSystem:      "Operating System",
  otg:                  "OTG Support",
  otherSensors:         "Other Sensors",
  peakBrightness:       "Peak Brightness",
  performance:          "Performance",
  pixelDensity:         "Pixel Density",
  priceList:            "Price List",
  quickCharging:        "Quick Charging",
  ram:                  "RAM",
  rearAutoFocus:        "Rear Autofocus",
  rearCamera:           "Rear Camera",
  rearCameraFeatures:   "Rear Camera Features",
  rearCameraSetup:      "Rear Camera Setup",
  rearFlash:            "Rear Flash",
  rearImageResolution:  "Rear Image Resolution",
  rearOis:              "Rear OIS",
  rearResolution:       "Rear Resolution",
  rearSettings:         "Rear Settings",
  rearShootingModes:    "Rear Shooting Modes",
  rearVideoFeatures:    "Rear Video Features",
  rearVideoRecording:   "Rear Video Recording",
  refreshRate:          "Refresh Rate",
  resolution:           "Resolution",
  ruggedness:           "Ruggedness",
  sar:                  "SAR",
  screenProtection:     "Screen Protection",
  screenSize:           "Screen Size",
  screenToBodyRatio:    "Screen-to-Body Ratio",
  sim1:                 "SIM1",
  sim2:                 "SIM2",
  simSize:              "SIM Size",
  simSlot:              "SIM Slot",
  stereoSpeakers:       "Stereo Speakers",
  storage:              "Storage",
  touchScreen:          "Touch Screen",
  usbConnectivity:      "USB Connectivity",
  usbType:              "USB Type",
  userRatings:          "User Ratings",
  voLte:                "VoLTE",
  waterproofing:        "Waterproofing",
  weight:               "Weight",
  wifi:                 "WiFi",
  wifiFeatures:         "WiFi Features"
};

export const sections = {
  summary: [
    "performance",
    "Display",
    "rearCamera",
    "frontCamera",
    "battery",
    "Storage",
    "expertRating",
    "userRatings",
    "benchMarks",
    "comparePrices"
],
  
  general: [
    "launchDate",
    "operatingSystem",
    "customUi"
  ],

  designKeys: [
    "dimensions",
    "weight",
    "material",
    "colours",
    "waterproofing",
    "ruggedness"
  ],
  
  performance: [
    "chipset",
    "cpu",
    "architecture",
    "graphics",
    "ram"
  ],
  display: [
    "displayType",
    "screenSize",
    "resolution",
    "aspectRatio",
    "pixelDensity",
    "screenToBodyRatio",
    "screenProtection",
    "bezelLessDisplay",
    "touchScreen",
    "peakBrightness",
    "refreshRate",
    "hdr"
  ],
  cameraRear:[
    "rearCameraSetup",
    "rearCamera",
    "rearAutoFocus",
    "rearOis",
    "rearFlash",
    "rearImageResolution",
    "rearSettings",
    "rearShootingModes",
    "rearCameraFeatures",
    "rearVideoRecording",
    "rearVideoFeatures"
  ],
  cameraFront: [
    "frontCameraSetup",
    "frontCamera",
    "frontAutofocus",
    "frontFlash",
    "frontResolution",
    "frontVideo"
  ],
  battery: [
    "battery",
    "batteryCapacity",
    "batteryRemovable",
    "quickCharging",
    "usbConnectivity",
    "usbType",
    "batteryType",
    "batteryTalkTime"
  ],

  storageKeys: [
    "internalMemory",
    "expandable",
    "otg",
    "storage",
    "availableStorage"
  ],

   nwcKeys: [
    "simSlot",
    "simSize",
    "networkSupport",
    "voLte",
    "sim1",
    "sim2",
    "sar",
    "wifi",
    "wifiFeatures",
    "bluetooth",
    "gps",
    "nfc",
    "usbConnectivity"
  ],

   multimediaKeys: [
    "fmRadio",
    "stereoSpeakers",
    "loudSpeaker",
    "audioJack",
    "audioFeatures"
  ],

   sensorsKeys: [
    "fingerprintSensor",
    "fingerprintPosition",
    "fingerprintType",
    "otherSensors"
  ]

};

