name: Scrape Phone Specs

on:
  workflow_dispatch:
    inputs:
      specs_url:
        description: "Please enter the specs URL to scrape"
        required: true
        type: string

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install cloudscraper lxml

      - name: Run scraper
        run: |
          python app/components/scraper.py "${{ github.event.inputs.specs_url }}"
